Add initial crawl on connect
Codeinwp/optimole-wp pull request #472
Opened 2023-02-16 18:50 UTC by HardeepAsrani

### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
This crawls images when you connect to Optimole service. More details here: [add link]
 
 

Closes https://github.com/Codeinwp/optimole-service/issues/643.

### How to test the changes in this Pull Request:
- Details on Lambda repo.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-02-23 14:41 UTC, GrigoreMihai requested changes
Overall it looks good just those small mentions.

2023-02-23 14:41 UTC, GrigoreMihai commented on inc/rest.php
> +	 * @return boolean True if no more posts left to receive, false if there are more left.
This response should be `WP_REST_Response` , it's not breaking anything but just to be accurate.

2023-02-23 19:02 UTC, HardeepAsrani commented on inc/api.php
> +	private $onboard_api_root = 'https://onboard.ha.optml.cloud/onboard_api/';
Yea, sorry, forgot to replace ha. subdomain.

2023-02-24 07:34 UTC, GrigoreMihai requested changes

2023-02-24 07:34 UTC, GrigoreMihai commented on inc/api.php
> +	private $onboard_api_root = 'https://onboard.i.optml.cloud/onboard_api/';
This needs to be `https://onboard.i.optimole.com/onboard_api/` .

2023-02-24 07:48 UTC, GrigoreMihai commented
For solving the conflicts I would recommend to first merge https://github.com/Codeinwp/optimole-wp/pull/478 on development and then sync.

2023-02-24 14:24 UTC, GrigoreMihai approved these changes

2023-02-27 08:31 UTC, HardeepAsrani commented
Is anything else needed here, do we put it for QA testing or something else? @GrigoreMihai

2023-02-27 08:38 UTC, GrigoreMihai commented
> Is anything else needed here, do we put it for QA testing or something else? @GrigoreMihai

We can put it for testing after the staging deploy build finishes https://github.com/Codeinwp/optimole-lambda-functions/actions/runs/4280421992/jobs/7452172229 .

I would also add a bit more details about how to test, but it's just a suggestion.

2023-03-01 14:32 UTC, irinelenache commented
@HardeepAsrani @GrigoreMihai I tried to test it but i'm not sure it worked. Am i supposed to test using the API key from https://staging-dashboard.optimole.com/ and the [test plugin](https://github.com/Codeinwp/optimole-test)?

2023-03-01 14:48 UTC, GrigoreMihai commented
> @HardeepAsrani @GrigoreMihai I tried to test it but i'm not sure it worked. Am i supposed to test using the API key from https://staging-dashboard.optimole.com/ and the [test plugin](https://github.com/Codeinwp/optimole-test)?

Yup, the staging has the changes required, the testing plugin needed the constant for this API, updated it now, should work with the latest test plugin, sorry for this, I thought it was added by Hardeep there .

2023-03-03 07:47 UTC, irinelenache commented
@GrigoreMihai @HardeepAsrani Tested again and now everything works fine regarding this PR, thank you 🚀

2023-03-03 09:05 UTC, HardeepAsrani commented
Thank you @irinelenache, I'll fix the merge conflicts.

2023-04-04 18:55 UTC, merged